print("Hello, my name is Paul Hudsona nd I am lerning how to code in \"Python Arcade\".")
print("The way I downloaded these files is I went into GitHub and forked the repository.")
print("After I forked the repository its path was /WindyWizard515/learn-arcade-work,")
print("Once I forked the repository I cloned it onto my files in my home directory \"/home/paul\".")
print("After I cloned the repository I went to terminal and created a venv and downloaded the pip package \"arcade\",")
print("Then, I navigated to the repository \"learn-arcade-work\" and from there I opened VS code using the command \"code\".")
print("That is how I got here in this program in VS code!")